name:
  my-workflow

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]


jobs:
  job_01:
    runs-on: ubuntu-latest
    env: 
      MY_VAR: "my_value"


    steps:
      - name: First command
        env: 
          MY_VAR: "my_value"
        run: echo setting env. var.
      
      - name: Second command
        run: echo "The value is - $MY_VAR"


  job_02:
    runs-on: ubuntu-latest

    steps:
      - name: Reading from another job
        run: echo "The value is $MY_VAR"


